# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3b420810f6571b202fdb84521a18d18faba37dc2196dd14719af275f3cec553fda1310d181e3272a7c2fcf206007d3684d2755452e4a0cc4bc29f060f8af32e

test:
  secret_key_base: 8a31b04d1bdc3ea129fe09a2bc73422a5532a0f6b4def2efcf36563753a0b2e6f5023cc97892a1b721766e3da2267cb10010ca3537428f4e76bc1065101a541b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
